# SITE CONFIGURATION
baseurl: ""
url: "https://o-wigglyplay.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  title: 프로그래밍과 친해지기
  avatar: #타이틀 옆 아바타 아이콘
  favicon:
  gravatar: # Email MD5 hash
  description: "공부내용을 기록 및 작업 내용을 기록하는 블로그입니다." # used by search engines

  # Header and footer text
  header_text: >
     <h2>프로그래밍과 친해지기</h2>

     <p>어렵고 어색한 프로그래밍과 함께 친해지는 프로젝트</p>
  header_text_feature_image:
  footer_text: >
   CopyRight &copy <a href="https://github.com/O-WigglyPlay">O-Wigglyplay</a>

  # Icons
  rss: false
  email_address: dhehfud00@naver.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "/O-WigglyPlay"
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
